version: "3.5"

networks:
   skynet:

services:

   node-bff:
      build:
         context: demo-apps/node-bff/
      hostname: node-bff
      container_name: node-bff
      ports:
         - 5000:5000
      environment:
         NODE_ENV: "test"
         OTEL_SERVICE_NAME: "node-bff"
         OTEL_SERVICE_VERSION: "1.0.0"
         COLLECTOR_OPTIONS: $COLLECTOR_OPTIONS_DIRECT
         HOST_DOMAIN: $HOST_DOMAIN
      networks:
         - skynet

   java-api:
      build:
         context: demo-apps/java-api/
      hostname: java-api
      container_name: java-api
      ports:
         - 5001:5001
      environment:
         SPRING_PROFILES_ACTIVE: "test"
         OTEL_SERVICE_NAME: "java-api"
         OTEL_SERVICE_VERSION: "1.0.0"
         OTEL_TRACES_EXPORTER: "otlp"
         OTEL_METRICS_EXPORTER: "none"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_DIRECT
         OTEL_EXPORTER_OTLP_HEADERS: $OTEL_EXPORTER_OTLP_AUTHORIZATION_DIRECT
      networks:
         - skynet

   dotnet-api:
      build:
         context: demo-apps/dotnet-api/
      hostname: dotnet-api
      container_name: dotnet-api
      ports:
         - 5002:5002
      environment:
         ENVIRONMENT: "test"
         OTEL_TRACES_EXPORTER: "otlp"
         OTEL_METRICS_EXPORTER: "otlp"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_DIRECT
         OTEL_EXPORTER_OTLP_HEADERS: $OTEL_EXPORTER_OTLP_AUTHORIZATION_DIRECT
         OTEL_RESOURCE_ATTRIBUTES: "service.name=dotnet-api,service.version=1.0.0"
      networks:
         - skynet
