version: '3.5'

networks:
   skynet:

volumes:
   logs: {}
   elasticsearch-data: {}

services:

   elasticsearch:
      build:
         context: elasticsearch/
      hostname: elasticsearch
      container_name: elasticsearch
      volumes:
         - elasticsearch-data:/usr/share/elasticsearch/data
      restart: unless-stopped
      environment:
         ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ports:
         - 9200:9200
         - 9300:9300
      networks:
         - skynet

   test:
      build:
         context: test-service/
      hostname: test
      container_name: test
      ports:
         - 5001:5001
      expose:
         - 5002
      volumes:
         - logs:/var/log
      networks:
         - skynet

   otel:
      build:
         context: otel/
      hostname: otel
      container_name: otel
      restart: always
      ports:
         - 4317:4317
      volumes:
         - logs:/var/log
      networks:
         - skynet
      depends_on:
         - test

   logstash:
      build:
         context: logstash/
      container_name: logstash
      environment:
         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
         AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
         AWS_SECRET_KEY: $AWS_SECRET_KEY
      networks:
         - skynet
      depends_on:
         - elasticsearch

   kibana:
      build:
         context: kibana/
      hostname: kibana
      container_name: kibana
      restart: unless-stopped
      ports:
         - 5601:5601
      networks:
         - skynet
      depends_on:
         - elasticsearch
