version: "3.5"

networks:
   skynet:

volumes:
   logs: {}
   localstack-data: {}

services:

   node-bff:
      build:
         context: demo-apps/node-bff/
      hostname: node-bff
      container_name: node-bff
      ports:
         - 5000:5000
      environment:
         HOST_DOMAIN: $HOST_DOMAIN
         NODE_ENV: "test"
         COLLECTOR_OPTIONS: $COLLECTOR_OPTIONS_KINESIS
         OTEL_EXPORTER_OTLP_ENDPOINT_HOST: $OTEL_EXPORTER_OTLP_ENDPOINT_KINESIS_HOST
         OTEL_SERVICE_NAME: "node-bff"
         OTEL_SERVICE_VERSION: "1.0.0"
      networks:
         - skynet

   java-api:
      build:
         context: demo-apps/java-api/
      hostname: java-api
      container_name: java-api
      ports:
         - 5001:5001
      environment:
         SPRING_PROFILES_ACTIVE: "test"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_KINESIS_GRPC
         OTEL_RESOURCE_ATTRIBUTES: "service.name=java-api,service.version=1.0.0"
         OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED: "false"
         OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_METRICS_EXPORTER: "otlp"
         OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_TRACES_EXPORTER: "otlp"
      volumes:
         - logs:/var/log
      networks:
         - skynet

   dotnet-api:
      build:
         context: demo-apps/dotnet-api/
      hostname: dotnet-api
      container_name: dotnet-api
      ports:
         - 5002:5002
      environment:
         ENVIRONMENT: "test"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_KINESIS_HTTP
         OTEL_RESOURCE_ATTRIBUTES: "service.name=dotnet-api,service.version=1.0.0"
         OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED: "false"
         OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED: "false"
         OTEL_METRICS_EXPORTER: "none"
         OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_TRACES_EXPORTER: "otlp"
      volumes:
         - logs:/var/log
      networks:
         - skynet

   otel-front-kinesis:
      build:
         context: otel-front/
         args:
            OTEL_AGENT_CONFIG: "./otel-agent-config-kinesis.yaml"
      hostname: otel-front-kinesis
      container_name: otel-front-kinesis
      environment:
         AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
         AWS_SECRET_KEY: $AWS_SECRET_KEY
         AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
         LOCALSTACK_ENDPOINT_URL: $LOCALSTACK_ENDPOINT_URL
      restart: always
      ports:
         - 4317:4317
         - 4318:4318
         - 6831:6831
         - 8126:8126
         - 14268:14268
         - 54526:54526
      volumes:
         - logs:/var/log
      networks:
         - skynet
      depends_on:
         - localstack

   localstack:
      build:
         context: localstack/
      hostname: localstack
      container_name: localstack
      ports:
         - 4566:4566
         - 4510-4559:4510-4559
      environment:
         DEBUG: 1
         DOCKER_HOST: "unix:///var/run/docker.sock"
      volumes:
         - localstack-data:/var/lib/localstack
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - skynet

   logstash:
      build:
         context: logstash/
      container_name: logstash
      ports:
         - 8081:8081
         - 8082:8082
         - 8083:8083
      environment:
         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
         AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
         AWS_SECRET_KEY: $AWS_SECRET_KEY
         AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
         LOCALSTACK_ENDPOINT_URL: $LOCALSTACK_ENDPOINT_URL
         ELASTICSEARCH_ENDPOINT: $ELASTICSEARCH_ENDPOINT
         ELASTICSEARCH_API_KEY: $ELASTICSEARCH_API_KEY
         ELASTICSEARCH_INGEST_PIPELINE: $ELASTICSEARCH_INGEST_PIPELINE
         ELASTICSEARCH_DATA_STREAM_NAMESPACE: $ELASTICSEARCH_DATA_STREAM_NAMESPACE
         ELASTICSEARCH_DATA_STREAM_DATASET: $ELASTICSEARCH_DATA_STREAM_DATASET
         ELASTICAPM_ENDPOINT: $ELASTICAPM_ENDPOINT
         ELASTICAPM_API_KEY: $ELASTICAPM_API_KEY
      networks:
         - skynet
      depends_on:
         - localstack
