version: "3.5"

networks:
   skynet:

volumes:
   logs: {}

services:

   node-bff:
      build:
         context: demo-apps/node-bff/
      hostname: node-bff
      container_name: node-bff
      ports:
         - 5000:5000
      environment:
         NODE_ENV: "test"
         OTEL_SERVICE_NAME: "node-bff"
         OTEL_SERVICE_VERSION: "1.0.0"
         COLLECTOR_OPTIONS: $COLLECTOR_OPTIONS_AGENT_ELASTIC
         HOST_DOMAIN: $HOST_DOMAIN
      networks:
         - skynet

   java-api:
      build:
         context: demo-apps/java-api/
      hostname: java-api
      container_name: java-api
      ports:
         - 5001:5001
      environment:
         OTEL_SERVICE_NAME: "java-api"
         OTEL_SERVICE_VERSION: "1.0.0"
         OTEL_TRACES_EXPORTER: "otlp"
         OTEL_METRICS_EXPORTER: "none"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_AGENT_GRPC_ELASTIC
      networks:
         - skynet

   dotnet-api:
      build:
         context: demo-apps/dotnet-api/
      hostname: dotnet-api
      container_name: dotnet-api
      ports:
         - 5002:5002
      environment:
         ENVIRONMENT: "test"
         OTEL_TRACES_EXPORTER: "otlp"
         OTEL_METRICS_EXPORTER: "none"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_AGENT_HTTP_ELASTIC
         OTEL_RESOURCE_ATTRIBUTES: "service.name=dotnet-api,service.version=1.0.0"
      volumes:
         - logs:/var/log
      networks:
         - skynet

   otel-front-elastic:
      build:
         context: otel-front/
         args:
            OTEL_AGENT_CONFIG: "./otel-agent-config-elastic.yaml"
      hostname: otel-front-elastic
      container_name: otel-front-elastic
      environment:
         ELASTICSEARCH_CLOUD_ID: $ELASTICSEARCH_CLOUD_ID
         ELASTICSEARCH_ENDPOINT: $ELASTICSEARCH_ENDPOINT
         ELASTICAPM_ENDPOINT: $ELASTICAPM_ENDPOINT
         ELASTICSEARCH_API_KEY: $ELASTICSEARCH_API_KEY
      restart: always
      ports:
         - 4317:4317
         - 4318:4318
         - 6831:6831
         - 8126:8126
         - 14268:14268
      volumes:
         - logs:/var/log
      networks:
         - skynet
