version: "3.5"

networks:
   skynet:

services:

   node-bff:
      build:
         context: demo-apps/node-bff/
      hostname: node-bff
      container_name: node-bff
      ports:
         - 5000:5000
      environment:
         HOST_DOMAIN: $HOST_DOMAIN
         NODE_ENV: "dev"
         COLLECTOR_OPTIONS: $COLLECTOR_OPTIONS_DIRECT
         OTEL_SERVICE_NAME: "node-bff"
         OTEL_SERVICE_VERSION: "1.0.0"
      networks:
         - skynet

   java-api:
      build:
         context: demo-apps/java-api/
      hostname: java-api
      container_name: java-api
      ports:
         - 5001:5001
      environment:
         SPRING_PROFILES_ACTIVE: "test"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_DIRECT
         OTEL_EXPORTER_OTLP_HEADERS: $OTEL_EXPORTER_OTLP_AUTHORIZATION_DIRECT
         OTEL_RESOURCE_ATTRIBUTES: "service.name=java-api,service.version=1.0.0"
         OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED: "false"
         OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_METRICS_EXPORTER: "otlp"
         OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_TRACES_EXPORTER: "otlp"
      networks:
         - skynet

   dotnet-api:
      build:
         context: demo-apps/dotnet-api/
      hostname: dotnet-api
      container_name: dotnet-api
      ports:
         - 5002:5002
      environment:
         ENVIRONMENT: "test"
         OTEL_EXPORTER_OTLP_ENDPOINT: $OTEL_EXPORTER_OTLP_ENDPOINT_DIRECT
         OTEL_EXPORTER_OTLP_HEADERS: $OTEL_EXPORTER_OTLP_AUTHORIZATION_DIRECT
         OTEL_RESOURCE_ATTRIBUTES: "service.name=dotnet-api,service.version=1.0.0"
         OTEL_DOTNET_AUTO_LOGS_CONSOLE_EXPORTER_ENABLED: "false"
         OTEL_DOTNET_AUTO_METRICS_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_METRICS_EXPORTER: "otlp"
         OTEL_DOTNET_AUTO_TRACES_CONSOLE_EXPORTER_ENABLED: "true"
         OTEL_TRACES_EXPORTER: "otlp"
      networks:
         - skynet
