receivers:

   filelog:
      include: [ /var/log/*.txt ]

   # syslog:
   #    tcp:
   #       listen_address: "0.0.0.0:54526"
   #       protocol: rfc5424

   otlp:
      protocols:
         http:
         grpc:

   prometheus:
      config:
         scrape_configs:
            - job_name: 'node-bff'
              scrape_interval: 1m
              static_configs:
                 - targets: ['node-bff:5000']
            - job_name: 'java-api'
              scrape_interval: 1m
              metrics_path: /actuator/prometheus
              static_configs:
                 - targets: ['java-api:5001']
            - job_name: 'dotnet-api'
              scrape_interval: 1m
              static_configs:
                 - targets: ['dotnet-api:5002']

exporters:

   elasticsearch:
      cloudid: "${env:OTEL_EXPORTER_ELASTICSEARCH_CLOUD_ID}"
      endpoints: ["${env:OTEL_EXPORTER_ELASTICSEARCH_ENDPOINT}"]
      api_key: "${env:OTEL_EXPORTER_ELASTICSEARCH_API_KEY}"
      traces_index: ryan-index-001

   otlp/metrics:
      otlp:
         endpoint: "${env:OTEL_EXPORTER_ELASTICAPM_ENDPOINT}"
         headers:
            Authorization: "${env:OTEL_EXPORTER_ELASTICAPM_AUTHORIZATION}"

   otlp/traces:
      otlp:
         endpoint: "${env:OTEL_EXPORTER_ELASTICAPM_ENDPOINT}"
         headers:
            Authorization: "${env:OTEL_EXPORTER_ELASTICAPM_AUTHORIZATION}"

service:
   pipelines:
      logs/dotnet_and_java:
         receivers: [filelog]
         exporters: [elasticsearch]
      # logs/node:
      #    receivers: [syslog]
      #    exporters: [elasticsearch]
      metrics:
         receivers: [prometheus]
         exporters: [otlp/metrics]
      traces:
         receivers: [otlp]
         exporters: [otlp/traces]
