receivers:

   # dotnet and java logs are written to file on shared volume
   filelog:
      include: [ "/var/log/dotnet-api/*.txt", "/var/log/java-api/*.txt" ]

   # node.js logs are getting sent via syslog
   syslog:
      udp:
         listen_address: "0.0.0.0:54526"
      protocol: rfc3164
      location: UTC

   # traces and java metrics getting sent to otlp endpoint
   # java is using proto/grpc
   # dotnet and node are using proto/http
   otlp:
      protocols:
         http:
         grpc:

   # dotnet and node metrics getting scraped via prometheus receiver
   prometheus:
      config:
         scrape_configs:
            - job_name: 'node-bff'
              scrape_interval: 1m
              static_configs:
                 - targets: ['node-bff:5000']
            # Note: Java metrics are getting sent to otlp/grpc endpoint
            # - job_name: 'java-api'
            #   scrape_interval: 1m
            #   metrics_path: /actuator/prometheus
            #   static_configs:
            #      - targets: ['java-api:5001']
            - job_name: 'dotnet-api'
              scrape_interval: 1m
              static_configs:
                 - targets: ['dotnet-api:5002']

exporters:

   awskinesis/logs:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: logs
         region: us-east-1
      # max_records_per_batch: 1
      encoding:
         name: otlp_json

   awskinesis/metrics:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: metrics
         region: us-east-1
      encoding:
         name: otlp_proto

   awskinesis/traces:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: traces
         region: us-east-1
      encoding:
         name: otlp_proto

service:
   pipelines:
      logs/dotnet_and_java:
         receivers: [filelog]
         exporters: [awskinesis/logs]
      logs/node:
         receivers: [syslog]
         exporters: [awskinesis/logs]
      metrics/dotnet_and_node:
         receivers: [prometheus]
         exporters: [awskinesis/metrics]
      metrics/java:
         receivers: [otlp]
         exporters: [awskinesis/metrics]
      traces:
         receivers: [otlp]
         exporters: [awskinesis/traces]
