receivers:

   filelog:
      include: [ /var/log/*.txt ]

   otlp:
      protocols:
         http:
         grpc:

   prometheus:
      config:
         scrape_configs:
            - job_name: 'dotnet-api'
              scrape_interval: 1m
              static_configs:
                 - targets: ['dotnet-api:5002']

exporters:

   awskinesis/logs:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: logs
         region: us-east-1
      encoding:
         name: otlp_json

   awskinesis/metrics:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: metrics
         region: us-east-1
      encoding:
         name: otlp_proto

   awskinesis/traces:
      aws:
         kinesis_endpoint: ${env:LOCALSTACK_ENDPOINT_URL}
         stream_name: traces
         region: us-east-1
      encoding:
         name: otlp_proto

service:
   pipelines:
      logs:
         receivers: [filelog]
         exporters: [awskinesis/logs]
      metrics:
         receivers: [prometheus]
         exporters: [awskinesis/metrics]
      traces:
         receivers: [otlp]
         exporters: [awskinesis/traces]

