receivers:

  filelog:
    include: [ /var/log/*.txt ]

exporters:

  awskinesis:
    aws:
      kinesis_endpoint: http://192.168.99.106:4566
      stream_name: ryantestotelpoc
      region: eu-west-1
    encoding:
      name: otlp_json

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [awskinesis]
